/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DecorationMethodsRouteImport } from './routes/decoration-methods'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as OurWorkRouteImport } from './routes/our-work'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsCategoryIndexRouteImport } from './routes/products.$category.index'
import { Route as ProductsCategoryProductRouteImport } from './routes/products.$category.$product'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DecorationMethodsRoute = DecorationMethodsRouteImport.update({
  id: '/decoration-methods',
  path: '/decoration-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkRoute = OurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryIndexRoute = ProductsCategoryIndexRouteImport.update({
  id: '/products/$category/',
  path: '/products/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryProductRoute = ProductsCategoryProductRouteImport.update({
  id: '/products/$category/$product',
  path: '/products/$category/$product',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/decoration-methods': typeof DecorationMethodsRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/our-work': typeof OurWorkRoute
  '/quote': typeof QuoteRoute
  '/solutions': typeof SolutionsRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$category/$product': typeof ProductsCategoryProductRoute
  '/products/$category/': typeof ProductsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/decoration-methods': typeof DecorationMethodsRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/our-work': typeof OurWorkRoute
  '/quote': typeof QuoteRoute
  '/solutions': typeof SolutionsRoute
  '/products': typeof ProductsIndexRoute
  '/products/$category/$product': typeof ProductsCategoryProductRoute
  '/products/$category': typeof ProductsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/decoration-methods': typeof DecorationMethodsRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/our-work': typeof OurWorkRoute
  '/quote': typeof QuoteRoute
  '/solutions': typeof SolutionsRoute
  '/products/': typeof ProductsIndexRoute
  '/products/$category/$product': typeof ProductsCategoryProductRoute
  '/products/$category/': typeof ProductsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/decoration-methods'
    | '/faq'
    | '/how-it-works'
    | '/our-work'
    | '/quote'
    | '/solutions'
    | '/products/'
    | '/products/$category/$product'
    | '/products/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/decoration-methods'
    | '/faq'
    | '/how-it-works'
    | '/our-work'
    | '/quote'
    | '/solutions'
    | '/products'
    | '/products/$category/$product'
    | '/products/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/decoration-methods'
    | '/faq'
    | '/how-it-works'
    | '/our-work'
    | '/quote'
    | '/solutions'
    | '/products/'
    | '/products/$category/$product'
    | '/products/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DecorationMethodsRoute: typeof DecorationMethodsRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  OurWorkRoute: typeof OurWorkRoute
  QuoteRoute: typeof QuoteRoute
  SolutionsRoute: typeof SolutionsRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProductsCategoryProductRoute: typeof ProductsCategoryProductRoute
  ProductsCategoryIndexRoute: typeof ProductsCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decoration-methods': {
      id: '/decoration-methods'
      path: '/decoration-methods'
      fullPath: '/decoration-methods'
      preLoaderRoute: typeof DecorationMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work': {
      id: '/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OurWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category/': {
      id: '/products/$category/'
      path: '/products/$category'
      fullPath: '/products/$category/'
      preLoaderRoute: typeof ProductsCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category/$product': {
      id: '/products/$category/$product'
      path: '/products/$category/$product'
      fullPath: '/products/$category/$product'
      preLoaderRoute: typeof ProductsCategoryProductRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DecorationMethodsRoute: DecorationMethodsRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  OurWorkRoute: OurWorkRoute,
  QuoteRoute: QuoteRoute,
  SolutionsRoute: SolutionsRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProductsCategoryProductRoute: ProductsCategoryProductRoute,
  ProductsCategoryIndexRoute: ProductsCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
